### ISSUE TITLE
Implicitly unwrapped optional behavior

### ISSUE THREAD

**Issue by giacgbj** [isair/JSONHelper#18]
Hi,
   I'm extremely new to Swift, so please forgive me if what's I'm trying to accomplish is a pure heresy, but why doesn't the following code work (just copy it into JSONHelperTests.swift to test it)?
```swift
    func testBoolBang() {
        var property: Bool!
        property <<< dummyResponse["bool"]
        XCTAssertEqual(property, true, "Bool property should equal true")
    }
```
It should return "true" instead of "nil".

Am I wrong?

**Comment by isair** [comment]
No, you're not. JSONHelper's behavior with implicitly unwrapped optionals is undefined at this time though. I'll take a look into it but they are going to introduce some interesting problems. Other than that, I would not recommend using implicitly unwrapped optionals in situations where you need to deserialize data even if the library did work with them.
