### ISSUE TITLE
Swift 1.2 Support

### ISSUE THREAD

**Issue by ox** [isair/JSONHelper#31]
Hey there! XCode 6.3 was recently forced upon my machine and with it came Swift 1.2. JSONHelper doesn't comply with this new version of Swift, and I was wondering if there were any plans to update the library to be compliant. There don't seem to be a lot of changes required, but I don't want to duplicate work someone is already doing. I think I could make a PR, but my knowledge of Swift isn't great. 

![screen shot 2015-04-14 at 4 05 29 pm](https://cloud.githubusercontent.com/assets/103545/7146249/305598c6-e2c0-11e4-8386-3d448bd4c457.png)

**Comment by isair** [comment]
Hi ox, are you using the latest release?

**Comment by ox** [comment]
I set it to use the master branch and the build problems have stopped. Unfortunately the syntax is now pretty different. Thanks for your help.

**Comment by isair** [comment]
Just changing all operators to `<--` should make things work again. Do let me know if you run into more problems.
