### ISSUE TITLE
"application: JSONHelper" sometimes inserted for null values in JSON

### ISSUE THREAD

**Issue by ingling** [isair/JSONHelper#32]
We've got several computers using JSONHelper to parse JSON for Applescripts.

I've got some behavior that seems very strange to me.

Running the same version of the Applescript, and the same version of JSONHelper, on the same JSON data, on some computers it is returning the null values to Applescript as the name of the application. That is, the null values get returned as:
application "JSONHelper"
in the returned JSON data. This doesn't happen on other computers.

The files can be downloaded here:
https://www.dropbox.com/s/sgepla2fpspdnzq/JSONHelper_Issue.zip?dl=0

It's got the original JSON data, and the different responses returned by running that through JSONHelper on different computers. At least three computers are returning the version with "application: JSONHelper" substituted for all null values.

I'd appreciate any help/insight. Whatever's going on, I don't understand how I'm getting different results when I use the same JSON data with the same Applescript and the same version of JSONHelper.

Thanks in advance for any help.

**Comment by isair** [comment]
Could you check if you still have this issue using 1.5.4?

**Comment by ingling** [comment]
How do I get that? I installed through the App store and had checked for updates first. I see 1.5.4 here on Github but only the source... is that the only way it's available? I only program in Applescript. I downloaded the source and opened it in Xcode, but I've never used Xcode before and I'm having trouble figuring out how to save it as an executable. I can probably get a developer to help me. I'll give that a try, but is it not available as an Application?

**Comment by isair** [comment]
I see. The app in the MAS called JSON Helper, which I didn't know about until now, is not related to this library. Funny enough, seems like we both had bugs with the handling of null values. I was wondering why I couldn't see the product name being returned no matter what I tried. I am sorry that I can't help you on this matter; you might want to contact the owner of that app.

**Comment by ingling** [comment]
Oh, sorry! Nevermind.


On Apr 15, 2015, at 3:12 PM, Baris Sencan <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. The app in the MAS called JSON Helper, which I didn't know about until now, is not related to this library. Funny enough, seems like we both had bugs with the handling of null values. I was wondering why I couldn't see the product name being returned no matter what I tried. I am sorry that I can't help you on this matter; you might want to contact the owner of that app.
