### ISSUE TITLE
Not able to use `let`

### ISSUE THREAD

**Issue by rafalio** [isair/JSONHelper#40]
The readme says:
"// You can also use let instead of var if you want."

I don't find this to be the case. Changing a `var x` to a `let x` gives the error "Variable self.x passed by reference before being initialized".

How can I use `let x`?

**Comment by isair** [comment]
Sadly swift 1.2 broke that. Looks like a left-over comment, I apologize.

**Comment by rafalio** [comment]
Ah I see. Should we find a way to use `let` ? I always try to make as much as possible immutable and the `var`'s in my data declarations that I want to parse into JSON are making me uneasy.

**Comment by isair** [comment]
Sorry for replying so late, completely missed your comment. Sadly the current version of Swift only allows assigning to a `let` property directly inside an initializer. So trying to assign to a `let` property from a function called inside an initializer used to work in older versions, but not anymore. I haven't taken a look at Swift 2.0 yet, but there might be a way to do that there.
