### ISSUE TITLE
Swift 2.0 support?

### ISSUE THREAD

**Issue by lexrus** [isair/JSONHelper#41]
Hi @isair 

I used JSONHelper in my personal project. And I'd like to upgrade it to iOS 9 and Swift 2.0. Do you have any plan to move?

**Comment by isair** [comment]
I'll soon have the time to work on this project for a while again. During that time, I plan to finish up the changes in [dev-2.0.0](https://github.com/isair/JSONHelper/commits/dev-2.0.0) branch and then add a swift-2.0 branch.

**Comment by lexrus** [comment]
Awesome. Cant' wait to see it.

**Comment by isair** [comment]
Closed via c309424
