### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by ldi13** [isair/JSONHelper#45]
Hello JSONHelper team,

I saw that on your podspec, you added the tvOS support on the master, 4 days ago.
However, there is no new version uploaded since then.

Do you think it could be possible to publish a 1.7.0 of JSONHelper library on Cocoapods in order to ship this feature ?

Best regards,

Lorenzo.

**Comment by sts2055** [comment]
If you guys want I can push the new spec to Cocoapods' main spec repo. I'd just need your good-to-go @isair

**Comment by isair** [comment]
The release will be out in a few minutes. :+1: 

Closed via 0df9e02

**Comment by ldi13** [comment]
Hello @isair ,

Thank you very much for this new version and your reactivity.

Best,

Lorenzo.

**Comment by isair** [comment]
No problem!
