### ISSUE TITLE
Time zone handling of NSDate conversions

### ISSUE THREAD

**Issue by kamalkcspl246** [isair/JSONHelper#51]
Hi,

I am facing issue with datetime during parsing. I am getting UTC date in my server response and when i try to deserialize that, JSONHelper assume, it is system datetime.

for example, I am passing "2016-01-04 11:00:56" for deserialize which is UTC date. Now after deserialize, i am getting "2016-01-04 05:30:56 +0000" while it should be same "2016-01-04 11:00:56 +0000" And when convert in to string, it should show "2016-01-04 16:30:56"

My TimeZone is: 5:30+

Can you suggest, how can i achieve that? Where can I pass, date timezone info?

Thanks
Kamal Mittal

**Comment by isair** [comment]
When you are passing the time string, you might want to add the timezone info to the end. It automatically assumed the local time zone. In your case the string is evaluated as 11:00:56 GMT+5:30, so the resulting 5:30 GMT+0 is correct.
