### ISSUE TITLE
Not works with latest version of Xcode and Swift 2.2

### ISSUE THREAD

**Issue by albetoetecnia** [isair/JSONHelper#59]
I'm getting this error:

Module file was created by an older version of the compiler; rebuild 'JSONHelper' and try again:

**Comment by isair** [comment]
You should use the [dev-2.0.0](https://github.com/isair/JSONHelper/tree/dev-2.0.0) branch. I'll merge it after its README is finished, should be able to take care of that today.

**Comment by albetoetecnia** [comment]
Thanks! Now it's working properly!
