### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by ldi13** [isair/JSONHelper#61]
Hello @isair ,

Do you plan to port your Pod on Swift 3.0 ?
All the best,

Lorenzo.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/68465511976682/154919883752229)

**Comment by isair** [comment]
I do. Although, any pull requests are welcome as I’ll probably port it after OS X Sierra is officially out.

**Comment by jondwillis** [comment]
@isair macOS hit golden master the other day :)

**Comment by brstgt** [comment]
Are you still working on that project? Sierra is out for months and I don't see any commits since June 2016

**Comment by brstgt** [comment]
Ooops, my bad. I didn't see the 3.0 branch, but anyway: I guess there is no pod for it?

**Comment by isair** [comment]
No worries. You can specify in your Podfile to use a specific branch name.
I'll merge the branch to master and release a new version to CocoaPods
after I make some small changes to tests and such. I think I can find time
for that this weekend.

**Comment by brstgt** [comment]
Awesome! ThAnk you!

Am 08.02.2017 23:54 schrieb "Baris Sencan" <notifications@github.com>:
